### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [davgross/william-wells-brown_clotel#1]
- It looks like most/all `<i>` elements are missing semantics

    - Note that words used as words get double quotes, not italics https://standardebooks.org/manual/1.0.0/8-typography#8.2.9.1

    - Quotes and also italics is almost never necessary; one or the other is sufficient

- se modernize-spelling makes some changes; some should be accepted but the ones in verse should be rejected

- In general, we can remove the XML comments that are inline with the text. This is what the commit history is for; changes marked [Editorial] allow us to inspect the differences and reasons for the differences. We also have the production-notes element, so inline comments are triply redundant.

- You can add the marc `win` relator to Brown. If it's been supposed he wrote it, and there's no more evidence he didn't, then it's fine to add it.

- `<abbr class="name">` around your initial in the colophon

- In general if `<em>` is marking up a fragment of a clause, the ending punctuation goes outside of `</em>`.  For example `inviting you to partake the perils and glory of your <em>white fellow citizens, I expected much from you;</em>` should be `inviting you to partake the perils and glory of your <em>white fellow citizens, I expected much from you</em>;` This occurs in more than a few places, search with this regex `[!;\.,?]</em>`

- In the song in chapter 16, `<cite>` doesn't belong in `<header>`. Usually there's only one `<cite>` which is used as the source of the quote. You can just remove `<cite>` and leave `<p>`. Note that you have to apply text-align center and small caps to override the default poetry styling text-align.

- Is the preface a letter? If not then it doesn't need the sender or dateline semantics. It doesn't look like a letter to me.

**Comment by acabal** [comment]
Also please capitalize the half title according to the linter's rules. Then, you can add an se-lint-ignore.xml file for the remaining error which is an exception.

**Comment by davgross** [comment]
Fixed
